name: Container Build Azure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "GitHub Environment"
        required: true
        type: string

      BUILD_CONTEXT:
        description: "Docker build paths"
        type: string
        default: '[{"path":"./app","image":"app"},{"path":"./server","image":"server"}]'

      TAG_NAME:
        description: "Docker image tag"
        required: true
        type: string

jobs:
  prep_matrix:
    name: Prep Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        env:
          BUILD_CONTEXT: ${{ inputs.BUILD_CONTEXT }}

        run: |
          MATRIX_JSON=$(jq -n -c --argjson ctx "$BUILD_CONTEXT" '{include: $ctx}')
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    needs: [prep_matrix]

    environment: ${{ inputs.ENVIRONMENT }}

    strategy:
      matrix: ${{ fromJson(needs.prep_matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Metadata
        id: docker_meta
        uses: docker/metadata-action@v5

        with:
          images: ${{ vars.ACR_URL }}/${{ matrix.image }}

      - name: Lowercase Repository Name
        id: repo_format

        run: |
          echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login To GitHub Container Registry
        uses: docker/login-action@v3

        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login To Azure Container Registry
        uses: docker/login-action@v3

        with:
          registry: ${{ vars.ACR_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build And Push Docker Images
        uses: docker/build-push-action@v5

        with:
          context: ${{ matrix.path }}

          labels: ${{ steps.docker_meta.outputs.labels }}

          tags: |
            ghcr.io/${{ steps.repo_format.outputs.IMAGE_REPOSITORY }}/${{ matrix.image }}:${{ inputs.TAG_NAME }}
            ${{ vars.ACR_URL }}/${{ matrix.image }}:${{ inputs.TAG_NAME }}

          push: true